services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/clinic-nginx/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # 挂载配置文件
      - /data/nginx-key:/etc/letsencrypt  # 证书存放目录
    depends_on:
      - clinic-app
    networks:
      - clinic-network

networks:
  clinic-network:
    external: true