name: Deploy to Aliyun Server

on:
  push:
    branches:
      - main  # 或者你部署的分支，比如 master

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Set up SSH key for Aliyun
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ALIYUN_SSH_KEY }}" > ~/.ssh/wzy.pem
          chmod 600 ~/.ssh/wzy.pem
          ssh-keyscan -H 39.106.136.220 >> ~/.ssh/known_hosts  # 添加阿里云服务器的公钥
        env:
          ALIYUN_SSH_KEY: ${{ secrets.ALIYUN_SSH_KEY }}  # 使用 GitHub Secrets

      - name: Deploy to Aliyun
        run: |
          ssh -i ~/.ssh/wzy.pem root@39.106.136.220 "cd /home/clinic-nginx && git pull && docker compose down && docker compose up -d"
